# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:20.9.0-browsers

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-v1-{{ checksum "yarn.lock" }}

      - run:
          command: yarn install
          name: Install Dependencies
    
      - save_cache:
          key: dependency-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            # Cache Chromium (which is downloaded and used by Puppeteer) so that it can be reused between builds.
            # If it isn't cached, then the test process will crash when running a cached version of Puppeteer as
            # Puppeteer only downloads Chromium when it is first installed.
            - ~/.cache/puppeteer

      - run:
          command: yarn build
          name: Build Assets

      - run:
          command: yarn test
          name: Run Tests

workflows:
  build-and-test:
    jobs:
      - build_and_test
