# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:20.9.0-browsers
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-version: v1.2
      - run:
          command: yarn install
          name: Install Dependencies
      - run:
          command: yarn build
          name: Build Assets
      - run:
          command: yarn test
          name: Run Tests

workflows:
  build-and-test:
    jobs:
      - build_and_test
